# Tak_OS · hyprlock.nix — Screen lock integration (hyprlock + hypridle config)
# github.com/tak0dan/Tak_OS · GNU GPLv3
# =============================================================================
#                         Hyprlock / Hypridle Module
# =============================================================================
#
# Loaded exclusively when features.hyprland = true (see configuration.nix).
#
# Responsibilities:
#   • Generates ~/.config/hypr/hypridle.conf for every user in
#     features.home-manager-users, driven by two sub-flags inside features.hypr:
#
#       features.hypr.lock = { enable = bool; timeout = int; }
#         enable  — whether hyprlock is invoked on idle / sleep
#         timeout — seconds of idle before screen locks
#                   (a "you are idle" warning fires 60 s before the lock)
#
#       features.hypr.idle — whether to write hypridle.conf at all
#         Set to false to leave the file unmanaged (user edits survive rebuilds).
#
#   • hyprlock package installation is handled by modules/system-packages.nix
#     (features.hypr.lock.enable gates it there).
#
# The file is written via a system activation script (runs as root on every
# rebuild), so it always reflects the current feature flags.
#
# =============================================================================
{ lib, pkgs, features, ... }:

lib.mkIf (features.hyprland && features.hypr.idle) {

  system.activationScripts.hypridle-config = {
    deps = [];
    text =
      let
        lockSecs = features.hypr.lock.timeout;
        warnSecs = lockSecs - 60;

        confFile = pkgs.writeText "hypridle.conf" ''
          # Generated by Tak_OS · modules/hyprlock.nix
          # Edit features.hypr.lock / features.hypr.idle in /etc/nixos/configuration.nix.
          # Manual edits will be overwritten on the next rebuild.

          $iDIR="$HOME/.config/swaync/images/ja.png"

          general {
            ${lib.optionalString features.hypr.lock.enable
              "lock_cmd            = pidof hyprlock || hyprlock"}
            before_sleep_cmd    = loginctl lock-session
            after_sleep_cmd     = hyprctl dispatch dpms on
            ignore_dbus_inhibit = false
          }

          # Idle warning — fires ${toString warnSecs}s before lock
          listener {
            timeout    = ${toString warnSecs}
            on-timeout = notify-send -i $iDIR " You are idle!"
            on-resume  = notify-send -i $iDIR " Oh! you're Back" " Hello !!!"
          }

          ${lib.optionalString features.hypr.lock.enable ''
          # Screen lock — fires after ${toString lockSecs}s of idle
          listener {
            timeout    = ${toString lockSecs}
            on-timeout = loginctl lock-session
          }
          ''}
        '';
      in
      lib.concatMapStrings (user: ''
        mkdir -p /home/${user}/.config/hypr
        cp -f ${confFile} /home/${user}/.config/hypr/hypridle.conf
        chown ${user}:users /home/${user}/.config/hypr/hypridle.conf 2>/dev/null || true
      '') features.home-manager-users;
  };

}
