{ config, pkgs, ... }:
{
  imports = [
    ./.modules/adw-bluetooth.nix
    ./.modules/blueman.nix
    ./.modules/discover-overlay.nix
    ./.modules/docker.nix
    ./.modules/eclipse-mat.nix
    ./.modules/eclipses.eclipse-committers.nix
    ./.modules/eclipses.eclipse-cpp.nix
    ./.modules/eclipses.eclipse-dsl.nix
    ./.modules/eclipses.eclipse-embedcpp.nix
    ./.modules/eclipses.eclipse-java.nix
    ./.modules/eclipses.eclipse-jee.nix
    ./.modules/eclipses.eclipse-modeling.nix
    ./.modules/eclipses.eclipse-platform.nix
    ./.modules/eclipses.eclipse-rcp.nix
    ./.modules/eclipses.eclipse-sdk.nix
    ./.modules/flatpak.nix
    ./.modules/gtk-pipe-viewer.nix
    ./.modules/krita.nix
    ./.modules/nano.nix
    ./.modules/nodejs.nix
    ./.modules/pnpm.nix
    ./.modules/python3.nix
    ./.modules/steam.nix
    ./.modules/swww.nix
    ./.modules/wallust.nix
  ];
}
