# ===========================================================
#  Tak_OS — system user: tak_2
#  Generated by the Tak_OS installer. Safe to edit.
#  Re-run: sudo /etc/nixos/scripts/install.sh  to regenerate.
#  Then:   sudo nixos-rebuild switch
#
#  Add per-user packages to the packages list below.
# ===========================================================
{ pkgs, lib, ... }:
{
  users.users.tak_2 = {
    isNormalUser = true;
    description  = "Tester for tak_1";
    shell        = pkgs.zsh;
    extraGroups  = [
      "networkmanager"
      "vboxusers"
      "docker"
      "audio"
      "video"
      "input"
      "plugdev"
    ];
    packages = [
      # pkgs.kate
    ];
  };
}
