#!/usr/bin/env bash
# Tak_OS · fix-users-nix.sh — rebuild users-declared hub from existing declarations
# github.com/tak0dan/Tak_OS · GNU GPLv3
# Run as root: sudo /etc/nixos/scripts/fix-users-nix.sh
set -euo pipefail
[[ "${EUID}" -ne 0 ]] && { echo "Run as root: sudo $0"; exit 1; }

USERS_DIR="/etc/nixos/users-declared"
mkdir -p "$USERS_DIR"

echo "[*] Rebuilding users hub in $USERS_DIR ..."

mapfile -t USER_FILES < <(find "$USERS_DIR" -maxdepth 1 -type f -name '*.nix' \
  ! -name 'default.nix' ! -name 'user-modules.nix' ! -name 'user-list.nix' ! -name 'extra-users.nix' \
  | sort)

{
  printf '# Generated by Tak_OS helper\n[ '
  for file in "${USER_FILES[@]}"; do
    base="$(basename "$file" .nix)"
    printf '"%s" ' "$base"
  done
  printf ']\n'
} > "$USERS_DIR/user-list.nix"

echo "[*] Writing $USERS_DIR/default.nix ..."
cat > "$USERS_DIR/default.nix" << 'NIX'
# Generated by Tak_OS helper — users hub
{ ... }:
{
  imports = [
    ./user-modules.nix
  ];
}
NIX

echo "[*] Writing $USERS_DIR/user-modules.nix ..."
{
  printf '# Generated by Tak_OS helper — aggregated imports\n{ ... }:\n{\n  imports = [\n'
  for file in "${USER_FILES[@]}"; do
    printf '    ./%s\n' "$(basename "$file")"
  done
  [[ -f "$USERS_DIR/extra-users.nix" ]] && printf '    ./extra-users.nix\n'
  printf '  ];\n}\n'
} > "$USERS_DIR/user-modules.nix"

chown root:root "$USERS_DIR"/*.nix 2>/dev/null || true
chmod 644 "$USERS_DIR"/*.nix 2>/dev/null || true

echo "[✓] Done. Now run: sudo nixos-rebuild dry-run"
