#!/usr/bin/env bash
# Tak_OS · fix-users-nix.sh — rewrite users-declared/ .nix files as proper NixOS modules
# github.com/tak0dan/Tak_OS · GNU GPLv3
# Run as root: sudo /etc/nixos/scripts/fix-users-nix.sh
set -euo pipefail
[[ "${EUID}" -ne 0 ]] && { echo "Run as root: sudo $0"; exit 1; }

USERS_DIR="/etc/nixos/users"
mkdir -p "$USERS_DIR"

echo "[*] Rewriting $USERS_DIR/tak_1.nix as NixOS module..."
cat > "$USERS_DIR/tak_1.nix" << 'NIX'
# ===========================================================
#  Tak_OS — system user: tak_1
#  Generated by the Tak_OS installer. Safe to edit.
#  Re-run: sudo /etc/nixos/scripts/install.sh  to regenerate.
#  Then:   sudo nixos-rebuild switch
#
#  Add per-user packages to the packages list below.
# ===========================================================
{ pkgs, lib, ... }:
{
  users.users.tak_1 = {
    isNormalUser = true;
    description  = "Elder Evil";
    shell        = pkgs.zsh;
    extraGroups  = [
      "wheel"           # sudo / admin
      "networkmanager"  # WiFi + VPN without sudo
      "vboxusers"       # VirtualBox
      "docker"          # Docker
      "audio"
      "video"
      "input"
    ];
    packages = [
      # pkgs.kate
    ];
  };
}
NIX

echo "[*] Rewriting $USERS_DIR/tak_2.nix as NixOS module..."
cat > "$USERS_DIR/tak_2.nix" << 'NIX'
# ===========================================================
#  Tak_OS — system user: tak_2
#  Generated by the Tak_OS installer. Safe to edit.
#  Re-run: sudo /etc/nixos/scripts/install.sh  to regenerate.
#  Then:   sudo nixos-rebuild switch
#
#  Add per-user packages to the packages list below.
# ===========================================================
{ pkgs, lib, ... }:
{
  users.users.tak_2 = {
    isNormalUser = true;
    description  = "Tester for tak_1";
    shell        = pkgs.bash;
    extraGroups  = [
      "networkmanager"  # WiFi + VPN without sudo
      "audio"
      "video"
      "input"
    ];
    packages = [
      # pkgs.kate
    ];
  };
}
NIX

echo "[*] Writing $USERS_DIR/user-list.nix..."
cat > "$USERS_DIR/user-list.nix" << 'NIX'
# ===========================================================
#  Tak_OS — user list
#  Generated by the Tak_OS installer. Do not edit manually.
#  Re-run: sudo /etc/nixos/scripts/install.sh  to regenerate.
#
#  Used by hm-users.nix and wlogout.nix (home-manager-users).
# ===========================================================
[ "tak_1" "tak_2" ]
NIX

chown root:root "$USERS_DIR"/*.nix
chmod 644 "$USERS_DIR"/*.nix
echo "[✓] Done. Now run: sudo nixos-rebuild dry-run"
