# Tak_OS · autogenerated.nix — Auto-generated package list (do not edit)
# github.com/tak0dan/Tak_OS · GNU GPLv3
{ pkgs }:
with pkgs; [
    adw-bluetooth
    bat
    blueman
    discover-overlay
    docker
    eclipse-mat
    eclipses.eclipse-committers
    eclipses.eclipse-cpp
    eclipses.eclipse-dsl
    eclipses.eclipse-embedcpp
    eclipses.eclipse-java
    eclipses.eclipse-jee
    eclipses.eclipse-modeling
    eclipses.eclipse-platform
    eclipses.eclipse-rcp
    eclipses.eclipse-sdk
    flatpak
    gtk-pipe-viewer
    krita
    libsForQt5.qtmultimedia
    nodejs
    perl5Packages.PlackMiddlewareFixMissingBodyInRedirect
    pnpm
    python3
    python313Packages.ifconfig-parser
    python313Packages.pip
    python314Packages.ifconfig-parser
#    steam
    swww
    unixtools.ifconfig
    wallust
]
